Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'welcome#startpage'
  get '/shelters', to: 'shelters#index'
  get 'shelters/new', to: 'shelters#new'
  post '/shelters', to: 'shelters#create'
  get '/shelters/:id', to: 'shelters#show'
  get '/shelters/:id/edit', to: 'shelters#edit'
  patch '/shelters/:id', to: 'shelters#update'
  delete '/shelters/:id', to: 'shelters#destroy'
  get '/pets', to: 'pets#index'
  get '/shelters/:id/pets', to: 'shelterpets#index'
  get '/shelters/:id/pets/new', to: 'pets#new'
  post '/shelters/:id/pets', to: 'pets#create'
  get '/pets/:id', to: 'pets#show'
  get '/pets/:id/edit', to: 'pets#edit'
  patch '/pets/:id', to: 'pets#update'
  delete '/pets/:id', to:'pets#destroy'
  get '/shelters/:id/new-review', to: 'reviews#new'
  post '/shelters/:id', to: 'reviews#create'
  get '/shelters/:id/edit-review/:review_id', to: 'reviews#edit'
  get 'reviews/:id', to: 'reviews#show'
  patch '/reviews/:id', to: 'reviews#update'
  delete '/reviews/:id', to: 'reviews#destroy'
  get '/favorites', to: 'favorites#index'
  patch '/favorites/:pet_id', to: 'favorites#update'
  delete '/favorites/:pet_id', to: 'favorites#destroy'
  delete '/favorites', to: 'favorites#delete_all'
  get '/application/new', to: 'petapplications#new'
  post '/favorites', to: 'petapplications#create'
  get '/application/:id', to: 'petapplications#show'
  get '/pets/:id/applications', to: 'petapplications#index'
end
